### ISSUE TITLE
请问还有效吗?

### ISSUE THREAD

**Issue by Fsouth** [BlueSkyXN/TencentCloud-Renew#2]
用了一下,不知道是我操作问题还是已经失效的原因,没有成功

**Comment by Fsouth** [comment]
oh,可惜的是我没有优惠券,
能帮忙点一下吗,您也能获得代金券
https://cloud.tencent.com/act/lighthouse?group_sn=6ef47380a7689ef0cc4a8a603e4d4340

**Comment by BlueSkyXN** [comment]
肯定有啊

> oh,可惜的是我没有优惠券,
> 能帮忙点一下吗,您也能获得代金券
> https://cloud.tencent.com/act/lighthouse?group_sn=6ef47380a7689ef0cc4a8a603e4d4340
